# Generated by Django 3.2 on 2021-12-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('lightpink', 'lightpink'), ('lightgreen', 'lightgreen'), ('orange', 'orange'), ('yellow', 'yellow'), ('lightgoldenrodyellow', 'lightyellow'), ('green', 'green'), ('blue', 'blue'), ('Indigo', 'indigo'), ('white', 'white')], max_length=150),
        ),
    ]
