# Generated by Django 3.2 on 2021-12-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_theme_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='text_color',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('lightpink', 'light pink'), ('lightgreen', 'light green'), ('orange', 'orange'), ('yellow', 'yellow'), ('lightgoldenrodyellow', 'light yellow'), ('green', 'green'), ('blue', 'blue'), ('lightblue', 'light blue'), ('Indigo', 'indigo'), ('white', 'white'), ('black', 'black')], default='black', max_length=150),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('lightpink', 'light pink'), ('lightgreen', 'light green'), ('orange', 'orange'), ('yellow', 'yellow'), ('lightgoldenrodyellow', 'light yellow'), ('green', 'green'), ('blue', 'blue'), ('lightblue', 'light blue'), ('Indigo', 'indigo'), ('white', 'white'), ('black', 'black')], default='white', max_length=150),
        ),
    ]
